import { MODULE_NAME, VERSION } from './js/constants.js';
import { loadSettings, getAvailableProfiles, refreshPresets, settings } from './js/state.js';
import { renderPolycephThoughts, syncHiddenMessageVisibility } from './js/ui.js';
import { addSettingsUI } from './js/settings-ui.js';
import { startPipeline, runPipeline } from './js/engine.js';
import { injectChatPipelineSelector, updateChatSelectorOptions, updateSendButtonVisibility } from './js/chat-ui.js';

// -------------------------------------------------------------------------
// Interception Hook
// -------------------------------------------------------------------------

export async function interceptSend(e) {
    console.log(`[${MODULE_NAME}] interceptSend triggered`, e.type);
    if (settings.activePipelineId === 'none') {
        console.log(`[${MODULE_NAME}] Polyceph set to 'None', skipping intercept.`);
        return;
    }

    const textarea = document.getElementById('send_textarea');
    if (!textarea) return;

    if (e.type === 'keydown' && (e.key !== 'Enter' || e.shiftKey)) {
        return;
    }

    let text = textarea.value.trim();
    if (text.startsWith('/')) {
        console.debug(`[${MODULE_NAME}] Slash command detected, bypassing Polyceph intercept.`);
        return;
    }

    const context = SillyTavern.getContext();

    if (!text) {
        // If text is empty, check if last message is from user to re-trigger
        const lastMsg = context.chat[context.chat.length - 1];
        if (lastMsg) {
            // ALWAYS prevent default if Polyceph is active on an empty send
            e.preventDefault();
            e.stopPropagation();
            e.stopImmediatePropagation();

            if (lastMsg.is_user && !lastMsg.extra?.polyceph_typing) {
                console.log(`[${MODULE_NAME}] Empty input detected. Re-triggering pipeline on last user message.`);

                text = lastMsg.mes;
                if (!lastMsg.extra) lastMsg.extra = {};
                lastMsg.extra.polyceph_typing = true;
                lastMsg.extra.polyceph_active_tasks = [];

                if (typeof context.updateMessageBlock === 'function') {
                    context.updateMessageBlock(context.chat.length - 1, lastMsg);
                }

                try {
                    await startPipeline(text);
                } catch (err) {
                    console.error(`[${MODULE_NAME}] Pipeline execution failed:`, err);
                    toastr.error('Pipeline execution failed. Check console for details.', 'Polyceph');
                }
            }
            return;
        }
        return;
    }

    e.preventDefault();
    e.stopPropagation();
    e.stopImmediatePropagation();
    textarea.value = '';

    const userName = context.name1 || 'User';
    const avatarStr = typeof context.getThumbnailUrl === 'function' && context.userAvatar ?
        context.getThumbnailUrl('avatar', context.userAvatar) : '';

    const message = {
        name: userName,
        is_user: true,
        is_system: false,
        send_date: typeof context.humanizedDateTime === 'function' ? context.humanizedDateTime() : new Date().toLocaleString(),
        mes: text,
        force_avatar: avatarStr,
        extra: { polyceph_typing: true, polyceph_active_tasks: [] },
        swipes: [text],
        swipe_id: 0,
        swipe_info: [{}]
    };

    setTimeout(async () => {
        console.log(`[${MODULE_NAME}] Adding user message. Chat length before:`, context.chat.length);
        context.chat.push(message);
        if (typeof context.addOneMessage === 'function') {
            await context.addOneMessage(message);
        } else {
            if (context.eventSource && context.eventTypes) {
                context.eventSource.emit(context.eventTypes.MESSAGE_RECEIVED, context.chat.length - 1);
            }
        }
        console.log(`[${MODULE_NAME}] User message added. Chat length after:`, context.chat.length);
        if (typeof context.saveChat === 'function') context.saveChat();

        // Stagger the pipeline start slightly
        setTimeout(async () => {
            try {
                await startPipeline(text);
            } catch (err) {
                console.error(`[${MODULE_NAME}] Pipeline execution failed:`, err);
                toastr.error('Pipeline execution failed. Check console for details.', 'Polyceph');
            }
        }, 50);
    }, 0);
}

function interceptSwipe(e) {
    if (settings.activePipelineId === 'none') return;

    const swipeRightBtn = e.target.closest('.swipe_right');
    if (!swipeRightBtn) return;

    const mesBlock = e.target.closest('.mes');
    if (!mesBlock) return;

    const mesId = parseInt(mesBlock.getAttribute('mesid'));
    const context = SillyTavern.getContext();
    const chatMsg = context.chat[mesId];

    // Check if this message was generated by Polyceph
    if (!chatMsg || !chatMsg.extra || chatMsg.extra.polyceph_source !== 'polyceph') return;

    const swipeId = chatMsg.swipe_id || 0;
    const swipesLen = chatMsg.swipes ? chatMsg.swipes.length : 1;

    // If we are at the last swipe and clicking right, generate a new one
    if (swipeId === swipesLen - 1) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();

        const batchId = chatMsg.extra.polyceph_batch;
        const userInput = chatMsg.extra.polyceph_input || '';

        // Find the user message that preceded this batch to attach the typing indicator to it
        let triggeringUserMesId = -1;
        for (let i = mesId - 1; i >= 0; i--) {
            if (context.chat[i]?.is_user) {
                triggeringUserMesId = i;
                break;
            }
        }

        toastr.info('Polyceph generation running...', 'Polyceph');
        runPipeline(userInput, batchId, triggeringUserMesId);
    }
}

function setupIntercepts() {
    const rightForm = document.getElementById('rightSendForm');
    const textArea = document.getElementById('send_textarea');

    if (rightForm) {
        const handleSendEvent = (e) => {
            const sendBtn = e.target.closest('#send_but');
            if (sendBtn && settings.interceptSend !== false) {
                interceptSend(e);
            }
        };

        // Use capture phase to intercept before ST's own listeners
        rightForm.addEventListener('click', handleSendEvent, true);
        rightForm.addEventListener('mousedown', handleSendEvent, true);

        // Monitor for DOM changes (like enabling impersonate button) to re-inject selector
        const observer = new MutationObserver(() => {
            if (!document.getElementById('polyceph-chat-pipeline-container')) {
                console.log(`[${MODULE_NAME}] Chat form changed, re-injecting selector.`);
                injectChatPipelineSelector();
            }
        });
        observer.observe(rightForm, { childList: true, subtree: true });
    }

    if (textArea) textArea.addEventListener('keydown', (e) => {
        if (settings.interceptEnter !== false) {
            interceptSend(e);
        }
    }, true);
    document.body.addEventListener('click', interceptSwipe, true);
}

// -------------------------------------------------------------------------
// Init
// -------------------------------------------------------------------------

async function init() {
    console.log(`[${MODULE_NAME}] Initializing Polyceph v${VERSION}...`);

    loadSettings();
    syncHiddenMessageVisibility();
    await getAvailableProfiles();
    refreshPresets();

    addSettingsUI();
    setupIntercepts();
    injectChatPipelineSelector(interceptSend);

    const context = SillyTavern.getContext();
    if (context.eventSource && context.eventTypes) {
        context.eventSource.on(context.eventTypes.CHAT_CHANGED, renderPolycephThoughts);
        context.eventSource.on(context.eventTypes.MESSAGE_RECEIVED, renderPolycephThoughts);
        context.eventSource.on(context.eventTypes.CHAT_COMPLETED, renderPolycephThoughts);

        // Update chat dropdown when settings are saved/changed
        context.eventSource.on(context.eventTypes.SETTINGS_UPDATED, () => {
            updateChatSelectorOptions();
            updateSendButtonVisibility();
        });

        // Listen for our custom settings change event
        context.eventSource.on('polyceph-settings-changed', () => {
            updateSendButtonVisibility();
        });
    }

    // Initial render for already existing messages
    renderPolycephThoughts();

    console.log(`[${MODULE_NAME}] Polyceph loaded.`);
}

if (typeof jQuery !== 'undefined') {
    jQuery(async () => { await init(); });
} else {
    window.addEventListener('DOMContentLoaded', init);
}
