import { logger } from '../logger.js';
import { encodeInvocations } from '../macros/utils.js';
import { DEFAULT_TOOL_RECURSION_LIMIT } from '../constants.js';
import { settings, getCapturedPresetName } from '../state.js';
import { waitForApiReady } from '../utils.js';
import { getMaxContextTokens, getMaxResponseTokens, countTokens, getActiveApi } from '../compat-shared.js';
import { generateViaCC, generateViaCCStreaming, isChatCompletionApi } from '../compat-chat.js';
import { parsePromptToMessages } from './parser.js';
import { LoopDetector } from './loop-detector.js';
import { extractToolCalls, executeToolCallsParallel } from './tool-handler.js';

import { getToolCallingModule } from '../compat-st.js';

/**
 * Executes a generation request through the SillyTavern API in "quiet" mode.
 * This avoids the main generation UI and allows background processing.
 *
 * @param {string} profileName - Connection profile to use.
 * @param {string} prompt - The assembled prompt text (with [[ROLE:...]] tags).
 * @param {string} [api=''] - API identifier.
 * @param {AbortSignal} [signal=null] - Abort signal.
 * @param {object} [options={}] - Streaming and loop detection options.
 * @param {boolean} [options.streaming] - Whether to attempt streaming (default: from settings).
 * @param {function} [options.onStream] - Called with {text, done} on each chunk.
 * @param {boolean} [options.antiLoop] - Enable loop detection (default: true).
 * @param {number} [options.loopThreshold] - Repetitions to trigger abort (default: from settings).
 * @returns {Promise<string>} The generated response text.
 */
export async function generateQuietly(profileName, prompt, api = '', signal = null, options = {}) {
    if (!profileName || profileName === 'none') {
        logger.debug('Template-only task detected (No LLM). Returning expanded template.');
        return prompt;
    }

    // Ensure API is ready and settled before starting generation
    // We only wait if we are actually calling an LLM
    await waitForApiReady(3000);

    if (signal && signal.aborted) throw new Error('Aborted');

    // Resolve streaming options from settings + overrides
    const outputType = options.outputType || 'internal';
    const allowTools = options.allowTools !== false;

    // Force non-streaming for tool-heavy tasks per requirement
    const forceNoStreaming = outputType === 'tool';
    const useStreaming = !forceNoStreaming && (options.streaming !== undefined ? options.streaming : (settings.enableStreaming !== false));

    const antiLoop = options.antiLoop !== undefined ? options.antiLoop : true;
    const loopThreshold = options.loopThreshold || settings.loopDetectionThreshold || 3;
    const onStream = options.onStream || null;
    const skipSuccessRecursion = !!options.skipSuccessRecursion;
    const hideSuccessResponse = !!options.hideSuccessResponse;

    try {
        const context = SillyTavern.getContext();

        // --- Compatibility: Token limit check ---
        const maxContext = await getMaxContextTokens();
        const maxResponse = getMaxResponseTokens();
        const maxPromptTokens = maxContext - maxResponse;

        const promptTokens = await countTokens(prompt);
        if (promptTokens > maxPromptTokens) {
            const errorMsg = `Prompt (${promptTokens} tokens) exceeds context budget (${maxPromptTokens} tokens). Generation aborted for safety.`;
            logger.error(errorMsg);
            throw new Error(errorMsg);
        }

        let responseData = "";

        // Parse prompt into role-based messages
        const messages = [...parsePromptToMessages(prompt, api)];
        const taskMessages = []; // Track only messages generated by THIS task loop for clean output

        // --- Tool Calling Support ---
        let ToolManager;
        try {
            const tmModule = await getToolCallingModule();
            ToolManager = tmModule?.ToolManager;
            if (!ToolManager && allowTools) {
                logger.warn('SillyTavern ToolManager not found. Tool calling features will be disabled for this generation.');
            }
        } catch (e) {
            logger.error('Failed to load SillyTavern ToolManager:', e);
        }

        const stCCSettings = context.chatCompletionSettings || {};
        const stRecurseLimit = stCCSettings.tool_call_recurse_limit;
        const toolReasoningMode = stCCSettings.tool_reasoning_mode || 'disabled';

        logger.debug(`Tool Reasoning Mode (Interleaved Thinking) in current preset: ${toolReasoningMode}`);

        let depth = 0;
        // Priority: 1. ST Preset Limit, 2. Existing Polyceph Setting (legacy), 3. Constant Fallback
        const maxDepth = stRecurseLimit !== undefined ? Number(stRecurseLimit) : (settings.toolRecursionLimit !== undefined ? settings.toolRecursionLimit : DEFAULT_TOOL_RECURSION_LIMIT);
        let finalResponse = "";
        let anyToolError = false;

        while (depth < maxDepth) {
            depth++;
            logger.info(`Starting tool recursion depth ${depth}/${maxDepth}`);

            if (signal && signal.aborted) throw new Error('Aborted');

            let tools = null;
            let tool_choice = null;

            // Only request tools if allowed for this task
            if (allowTools && ToolManager && typeof ToolManager.isToolCallingSupported === 'function' && ToolManager.isToolCallingSupported()) {
                const isOaiCompatible = isChatCompletionApi(api);

                // Prepare metadata for event listeners
                const generateData = {
                    model: isOaiCompatible ? (context.chatCompletionSettings?.openai_model || '') : '',
                    messages: messages,
                    tools: null,
                    tool_choice: null,
                    temperature: context.chatCompletionSettings?.temp_openai,
                    max_tokens: context.chatCompletionSettings?.openai_max_tokens || context.chatCompletionSettings?.max_tokens_openai,
                };

                // Use native ST registration if available (most robust)
                if (typeof ToolManager.registerFunctionToolsOpenAI === 'function') {
                    await ToolManager.registerFunctionToolsOpenAI(generateData);
                } else {
                    // Fallback: Manual collection
                    const availableTools = [];
                    for (const tool of (ToolManager.tools || [])) {
                        try {
                            if (typeof tool.shouldRegister === 'function' ? await tool.shouldRegister() : true) {
                                const toolDef = typeof tool.toFunctionOpenAI === 'function' ? tool.toFunctionOpenAI() : tool;
                                if (toolDef) availableTools.push(toolDef);
                            }
                        } catch (e) {
                            logger.warn('Failed to process tool definition:', tool, e);
                        }
                    }
                    if (availableTools.length > 0) {
                        generateData.tools = availableTools;
                        generateData.tool_choice = 'auto';
                    }
                }

                // Emit event to allow other extensions (like specialized tool managers) to modify
                if (context.eventSource && context.eventTypes?.CHAT_COMPLETION_SETTINGS_READY) {
                    await context.eventSource.emit(context.eventTypes.CHAT_COMPLETION_SETTINGS_READY, generateData);
                }

                tools = generateData.tools;
                tool_choice = generateData.tool_choice;

                if (tools && tools.length > 0) {
                    logger.debug('Tools to be sent:', tools);
                }
            }

            // --- Determine whether to use streaming or non-streaming ---
            const canStream = useStreaming && isChatCompletionApi(api);
            let loopDetector = null;

            if (canStream && antiLoop) {
                loopDetector = new LoopDetector(loopThreshold);
            }

            let responseData = null;
            let apiAttempt = 0;
            const maxApiRetries = settings.maxToolRetries || 0;
            const timeoutMs = settings.generationTimeoutMs !== undefined ? settings.generationTimeoutMs : 60000;

            while (apiAttempt <= maxApiRetries) {
                try {
                    if (canStream) {
                        // ========== STREAMING PATH ==========
                        logger.debug(`Using streaming generation path (attempt ${apiAttempt + 1}/${maxApiRetries + 1}).`);

                        const streamingChunkHandler = async (chunk) => {
                            // Feed loop detector
                            if (loopDetector && !chunk.done) {
                                loopDetector.feed(chunk.text.slice(loopDetector.getFullText().length));
                                if (loopDetector.isLooping()) {
                                    const info = loopDetector.getLoopInfo();
                                    logger.warn(`Loop detected during streaming: "${info.pattern}" (${info.repetitions}× at period ${info.patternLength})`);
                                    throw new Error('Loop detected');
                                }
                            }

                            // Forward to caller's stream handler
                            if (onStream) {
                                await onStream({ text: chunk.text, reasoning: chunk.reasoning, done: chunk.done });
                            }
                        };

                        const streamingPromise = generateViaCCStreaming(messages, signal, streamingChunkHandler, tools, tool_choice, api, false);

                        // Build race array for timeout + abort
                        const raceArr = [streamingPromise];

                        if (timeoutMs > 0) {
                            raceArr.push(new Promise((_, reject) => setTimeout(() => reject(new Error('Generation Timeout')), timeoutMs)));
                        }

                        const abortPromise = signal ? new Promise((_, reject) => {
                            if (signal.aborted) reject(new Error('Aborted'));
                            signal.addEventListener('abort', () => reject(new Error('Aborted')), { once: true });
                        }) : null;
                        if (abortPromise) raceArr.push(abortPromise);

                        const streamResult = await Promise.race(raceArr);

                        if (streamResult === null) {
                            // Streaming unavailable — fallback to non-streaming in next retry/loop pass
                            logger.info('Streaming returned null (unavailable). Falling back to non-streaming.');
                            responseData = await _generateNonStreaming(messages, tools, tool_choice, signal, timeoutMs, false);
                        } else {
                            logger.debug('Streaming path successfully returned result object.');
                            responseData = streamResult;
                        }
                    } else {
                        // ========== NON-STREAMING PATH ==========
                        logger.debug(`Streaming disabled or unsupported (attempt ${apiAttempt + 1}/${maxApiRetries + 1}). Using non-streaming generation path.`);
                        responseData = await _generateNonStreaming(messages, tools, tool_choice, signal, timeoutMs, false);
                    }

                    // If we got a response, check for errors
                    if (responseData?.error) {
                        const err = responseData.error;
                        throw new Error(err.message || JSON.stringify(err));
                    }

                    // If we got here, we have a valid response (or at least not an API error)
                    break;

                } catch (err) {
                    if (err.message === 'Aborted' || err.message === 'Loop detected') throw err;

                    apiAttempt++;
                    if (apiAttempt > maxApiRetries) throw err;

                    const delay = settings.retryDelayMs || 2000;
                    logger.warn(`API Turn ${depth} failed (attempt ${apiAttempt}/${maxApiRetries + 1}). Retrying in ${delay}ms...`, err);
                    await new Promise(r => setTimeout(r, delay));
                }
            }

            if (!responseData) {
                logger.warn(`Turn ${depth} returned no data.`);
                finalResponse = "(Generation returned empty)";
                break;
            }

            const assistantMessage = responseData?.choices?.[0]?.message;
            let turnReasoning = assistantMessage?.reasoning_content || assistantMessage?.reasoning || '';
            
            // Extract from reasoning_details if present (common in OpenRouter/Gemini)
            if (!turnReasoning && Array.isArray(assistantMessage?.reasoning_details)) {
                turnReasoning = assistantMessage.reasoning_details
                    .map(rd => rd.reasoning || rd.text || rd.data || '')
                    .join('\n');
            } else if (!turnReasoning && Array.isArray(responseData?.reasoning_details)) {
                 turnReasoning = responseData.reasoning_details
                    .map(rd => rd.reasoning || rd.text || rd.data || '')
                    .join('\n');
            }

            logger.debug(`Turn ${depth} response:`, responseData);

            // Extract tool calls from response
            const toolCalls = extractToolCalls(responseData);
            
            if (turnReasoning) {
                logger.debug(`Turn ${depth} reasoning found: ${turnReasoning.length} chars.`);
            }

            // Check for API-level errors (top level or in choices)
            if (responseData?.error) {
                const err = responseData.error;
                throw new Error(err.message || JSON.stringify(err));
            }
            if (responseData.choices?.[0]?.finish_reason === 'error') {
                const errorDetail = responseData.choices[0].native_finish_reason || 'Unknown API Error';
                throw new Error(`API returned an error: ${errorDetail}`);
            }

            if (toolCalls && toolCalls.length > 0 && ToolManager) {
                logger.debug(`Tool calls detected (depth ${depth}):`, toolCalls);

                // 1. Add assistant message to history (essential for next turns and output)
                const assistantMessage = responseData?.choices?.[0]?.message;
                const assistantHistoryItem = {
                    role: 'assistant',
                    content: assistantMessage?.content || '',
                    tool_calls: toolCalls
                };

                // Only include reasoning metadata in context if interleaved thinking is enabled
                if (toolReasoningMode !== 'disabled') {
                    assistantHistoryItem.reasoning_content = turnReasoning;
                    assistantHistoryItem.signature = assistantMessage?.signature || '';
                    assistantHistoryItem.toolSignatures = assistantMessage?.toolSignatures || {};
                }

                messages.push(assistantHistoryItem);
                taskMessages.push(assistantHistoryItem);

                // 2. Execute tools in parallel
                const { results, hasErrors } = await executeToolCallsParallel(ToolManager, toolCalls);
                if (hasErrors) anyToolError = true;

                // 3. Add tool results to history
                if (results && Array.isArray(results)) {
                    messages.push(...results);
                    taskMessages.push(...results);
                }

                depth++;
                logger.info(`Continuing generation loop: ${toolCalls.length} tool calls executed, Turn ${depth} follows.`);

                // If "No Success Recursion" is enabled and all tools succeeded, we can stop here
                if (options.skipSuccessRecursion && !hasErrors) {
                    logger.info('skipSuccessRecursion is true and tools succeeded. Ending task early.');
                    break;
                }

                continue; // Loop again with tool results
            }

            // No more tool calls, clean up and return
            if (responseData?._streaming) {
                // Streaming path: text is already extracted
                const rawText = responseData.choices?.[0]?.message?.content || '';
                if (typeof context.cleanUpMessage === 'function') {
                    finalResponse = context.cleanUpMessage({
                        getMessage: String(rawText),
                        isImpersonate: false,
                        isContinue: false,
                        displayIncompleteSentences: true,
                        includeUserPromptBias: false,
                        trimNames: true,
                        trimWrongNames: true,
                    });
                } else {
                    finalResponse = String(rawText);
                }
            } else {
                // Non-streaming path: extract message from data
                let rawText = '';
                if (typeof context.extractMessageFromData === 'function') {
                    rawText = context.extractMessageFromData(responseData, api || context.main_api);
                }

                // Fallback extraction if extractMessageFromData fails or returns something non-string
                if (typeof rawText !== 'string' || !rawText) {
                    rawText = responseData?.choices?.[0]?.message?.content || responseData?.choices?.[0]?.text || '';
                }

                if (typeof context.cleanUpMessage === 'function') {
                    finalResponse = context.cleanUpMessage({
                        getMessage: String(rawText),
                        isImpersonate: false,
                        isContinue: false,
                        displayIncompleteSentences: true,
                        includeUserPromptBias: false,
                        trimNames: true,
                        trimWrongNames: true,
                    });
                } else {
                    finalResponse = String(rawText);
                }

                // Inject API reasoning if present (append at end as requested)
                if (turnReasoning && !finalResponse.includes('<think>')) {
                    finalResponse += `\n\n<think>\n${turnReasoning}\n</think>`;
                }
            }
            break;
        }

        logger.debug('Generation loop finished. Final Response length:', finalResponse?.length || 0);

        // --- Success Enforcement ---
        // If tools were enabled and any failed, and we are in a strict mode, abort.
        // For now, we'll log it. If outputType is 'tool', success is critical.
        if (anyToolError && outputType === 'tool') {
            logger.warn('Tool execution encountered errors in a Tool Processor task. Proceeding to reconstruct history for UI visibility.');
            // Don't return early; let it fall through to reconstruct the history so thoughts are visible.
        }

        // If success response is hidden, return empty string
        if (options.hideSuccessResponse) {
            return '';
        }

        // Reconstruct output from taskMessages to ensure we only include Polyceph's own turns (no injections)
        const newMessages = taskMessages;

        if (options.hideToolHistory) {
            // Only send the "success object" (last turn's results or final response)
            if (options.skipSuccessRecursion) {
                const lastToolResults = newMessages.filter(m => m.role === 'tool');
                if (lastToolResults.length > 0) {
                    return lastToolResults.map(res => `[[ROLE:tool:${res.tool_call_id}]]\n${res.content}\n[[/ROLE]]`).join('\n\n');
                }
            }
            // Fallback to role-tagged final response
            if (finalResponse) {
                // Collect all reasoning from the task to show in the UI
                let accumulatedReasoning = '';
                for (const m of newMessages) {
                    if (m.role === 'assistant' && m.reasoning_content) {
                        accumulatedReasoning += (accumulatedReasoning ? '\n' : '') + m.reasoning_content;
                    }
                }

                let output = `[[ROLE:assistant]]\n`;
                if (accumulatedReasoning && !finalResponse.includes('<think>')) {
                    logger.debug(`Wrapping ${accumulatedReasoning.length} chars of accumulated reasoning in <think> tags.`);
                    output += `<think>\n${accumulatedReasoning}\n</think>\n\n`;
                }
                output += finalResponse;

                // Inject all tool calls from this task into the final assistant message for visualization
                for (const m of newMessages) {
                    if (m.role === 'assistant' && m.tool_calls) {
                        for (const tc of m.tool_calls) {
                            const resultMsg = newMessages.find(rm => rm.role === 'tool' && rm.tool_call_id === tc.id);
                            const result = resultMsg ? resultMsg.content : '(No result found)';
                            output += `\n\n<tool_call name="${tc.function.name}" args='${tc.function.arguments}'>\n${result}\n</tool_call>`;
                        }
                    }
                }
                return output + `\n[[/ROLE]]`;
            }

        } else {
            // Reconstruct full turn history with role tags
            if (newMessages.length > 0) {
                return newMessages.map(m => {
                    const role = m.role;
                    const roleSuffix = (role === 'tool' && m.tool_call_id) ? `:${m.tool_call_id}` : '';
                    let content = m.content || '';
                    if (role === 'assistant' && m.reasoning_content && !content.includes('<think>')) {
                        content += `\n\n<think>\n${m.reasoning_content}\n</think>`;
                    }

                    if (role === 'assistant' && m.tool_calls && m.tool_calls.length > 0) {
                        // Inject tool calls for UI visualization
                        for (const tc of m.tool_calls) {
                            const resultMsg = newMessages.find(rm => rm.role === 'tool' && rm.tool_call_id === tc.id);
                            const result = resultMsg ? resultMsg.content : '(No result found)';
                            content += `\n\n<tool_call name="${tc.function.name}" args='${tc.function.arguments}'>\n${result}\n</tool_call>`;
                        }
                        if (m.tool_calls && Array.isArray(m.tool_calls)) {
                            content += `\n[[INVOCATIONS:${encodeInvocations(m.tool_calls)}]]`;
                        }
                    }
                    return `[[ROLE:${role}${roleSuffix}]]\n${content.trim()}\n[[/ROLE]]`;
                }).join('\n\n');
            }

        }

        if (finalResponse !== undefined && finalResponse !== null) return finalResponse;
        return "(Generation returned empty)";

    } catch (err) {
        if (err.message === 'Aborted') throw err;
        if (err.message === 'Loop detected') throw err;

        // Parse deep SillyTavern/API error responses if available
        let errorDetail = err.message || 'Unknown error';
        if (err.response) {
            try {
                const parsed = typeof err.response === 'string' ? JSON.parse(err.response) : err.response;
                errorDetail = parsed.error?.message || parsed.message || JSON.stringify(parsed);
            } catch (e) {
                errorDetail = String(err.response);
            }
        }

        logger.error('Generation failed:', errorDetail, err);
        
        // If we have some history, return it so thoughts are visible, but prepend the error
        if (taskMessages.length > 0) {
            logger.warn('Reconstructing partial history after generation failure.');
            finalResponse = `(Error: ${errorDetail})`;
            // Fall through to the final return logic below (outside the try/catch)
        } else {
            throw new Error(errorDetail);
        }
    }

    // --- Final Output Reconstruction (Shared by success and partial failure) ---
    const newMessages = taskMessages;

    if (options.hideToolHistory) {
        // Only send the "success object" (last turn's results or final response)
        // Check if we had errors (either tool errors or the final API error)
        const hasAnyError = anyToolError || (finalResponse && finalResponse.includes('(Error:'));
        
        if (options.skipSuccessRecursion) {
            const lastToolResults = newMessages.filter(m => m.role === 'tool');
            if (lastToolResults.length > 0) {
                return lastToolResults.map(res => `[[ROLE:tool:${res.tool_call_id}]]\n${res.content}\n[[/ROLE]]`).join('\n\n');
            }
        }
        
        // Fallback to role-tagged final response
        let accumulatedReasoning = '';
        for (const m of newMessages) {
            if (m.role === 'assistant' && m.reasoning_content) {
                accumulatedReasoning += (accumulatedReasoning ? '\n' : '') + m.reasoning_content;
            }
        }

        let output = `[[ROLE:assistant]]\n`;
        if (accumulatedReasoning && (!finalResponse || !finalResponse.includes('<think>'))) {
            output += `<think>\n${accumulatedReasoning}\n</think>\n\n`;
        }
        output += (finalResponse || "(No response)");

        // Inject all tool calls
        for (const m of newMessages) {
            if (m.role === 'assistant' && m.tool_calls) {
                for (const tc of m.tool_calls) {
                    const resultMsg = newMessages.find(rm => rm.role === 'tool' && rm.tool_call_id === tc.id);
                    const result = resultMsg ? resultMsg.content : '(No result found)';
                    output += `\n\n<tool_call name="${tc.function.name}" args='${tc.function.arguments}'>\n${result}\n</tool_call>`;
                }
            }
        }
        return output + `\n[[/ROLE]]`;
    } else {
        // Reconstruct full turn history
        if (newMessages.length > 0) {
            return newMessages.map(m => {
                const role = m.role;
                const roleSuffix = (role === 'tool' && m.tool_call_id) ? `:${m.tool_call_id}` : '';
                let content = m.content || '';
                if (role === 'assistant' && m.reasoning_content && !content.includes('<think>')) {
                    content += `\n\n<think>\n${m.reasoning_content}\n</think>`;
                }

                if (role === 'assistant' && m.tool_calls && m.tool_calls.length > 0) {
                    for (const tc of m.tool_calls) {
                        const resultMsg = newMessages.find(rm => rm.role === 'tool' && rm.tool_call_id === tc.id);
                        const result = resultMsg ? resultMsg.content : '(No result found)';
                        content += `\n\n<tool_call name="${tc.function.name}" args='${tc.function.arguments}'>\n${result}\n</tool_call>`;
                    }
                    if (m.tool_calls && Array.isArray(m.tool_calls)) {
                        content += `\n[[INVOCATIONS:${encodeInvocations(m.tool_calls)}]]`;
                    }
                }
                return `[[ROLE:${role}${roleSuffix}]]\n${content.trim()}\n[[/ROLE]]`;
            }).join('\n\n') + (finalResponse && finalResponse.includes('(Error:') ? `\n\n[[ROLE:system]]\n${finalResponse}\n[[/ROLE]]` : '');
        }
    }

    if (finalResponse !== undefined && finalResponse !== null) return finalResponse;
    return "(Generation returned empty)";
}

/**
 * Internal helper: runs the non-streaming generation path with timeout/abort racing.
 * Extracted to avoid code duplication between the streaming fallback and non-streaming branch.
 */
async function _generateNonStreaming(messages, tools, tool_choice, signal, timeoutMs, noEmissions = false) {
    const apiPromise = generateViaCC(messages, tools, tool_choice, noEmissions);

    const abortPromise = signal ? new Promise((_, reject) => {
        if (signal.aborted) reject(new Error('Aborted'));
        signal.addEventListener('abort', () => reject(new Error('Aborted')), { once: true });
    }) : null;

    if (timeoutMs > 0) {
        const raceArr = [
            apiPromise,
            new Promise((_, reject) => setTimeout(() => reject(new Error('Generation Timeout')), timeoutMs))
        ];
        if (abortPromise) raceArr.push(abortPromise);
        return await Promise.race(raceArr);
    } else {
        return await (abortPromise ? Promise.race([apiPromise, abortPromise]) : apiPromise);
    }
}
